// Code generated by Slice Machine. DO NOT EDIT.

import CallToAction from './CallToAction';
import Content from './Content';
import ContentCenter from './ContentCenter';
import Featured from './Featured';
import Footer from './Footer';
import Header from './Header';
import HeroWithEmbed from './HeroWithEmbed';
import ImageWithParagraph from './ImageWithParagraph';
import LogoBrand from './LogoBrand';
import Navbar from './Navbar';
import Products from './Products';
import Testimonials from './Testimonials';
import VideoBanner from './VideoBanner';

export {
	CallToAction,
	Content,
	ContentCenter,
	Featured,
	Footer,
	Header,
	HeroWithEmbed,
	ImageWithParagraph,
	LogoBrand,
	Navbar,
	Products,
	Testimonials,
	VideoBanner,
};

export const components = {
	call_to_action: CallToAction,
	content: Content,
	content_center: ContentCenter,
	featured: Featured,
	footer: Footer,
	header: Header,
	hero_with_embed: HeroWithEmbed,
	image_with_paragraph: ImageWithParagraph,
	logo_brand: LogoBrand,
	navbar: Navbar,
	products: Products,
	testimonials: Testimonials,
	video_banner: VideoBanner,
};
